import { NextRequest, NextResponse } from "next/server";
import { requireSeller } from "@/lib/auth/seller-guard";
import { db } from "@/lib/db";
import { khataEntries } from "@/lib/db/schema";
import { eq, desc } from "drizzle-orm";
import { guardFeatureAccess, PlanFeatureError } from "@/lib/plans/plan-guards";
import { logger } from "@/lib/utils/logger";
import { z } from "zod";

const createKhataSchema = z.object({
    entryType: z.enum(['INCOME', 'EXPENSE', 'WITHDRAWAL', 'COMMISSION', 'REFUND', 'ADJUSTMENT']),
    category: z.string().min(1).max(100),
    description: z.string().min(1).max(500),
    amountRs: z.number().positive(),
    isCredit: z.boolean(),
    entryDate: z.string().regex(/^\d{4}-\d{2}-\d{2}$/, "Must be YYYY-MM-DD"),
});

export async function GET(req: NextRequest) {
    try {
        const guard = await requireSeller(req);
        if (!guard.ok) return guard.response;
        
        try {
            await guardFeatureAccess(guard.kitchen.id, 'digital_khata');
        } catch (error) {
            if (error instanceof PlanFeatureError) {
                return NextResponse.json({ error: error.message }, { status: 403 });
            }
            throw error;
        }

        const entries = await db.query.khataEntries.findMany({
            where: eq(khataEntries.kitchenId, guard.kitchen.id),
            orderBy: [desc(khataEntries.entryDate), desc(khataEntries.createdAt)],
            limit: 100,
        });

        return NextResponse.json({ success: true, entries });
    } catch (error) {
        logger.error("Failed to fetch khata entries", { error });
        return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
    }
}

export async function POST(req: NextRequest) {
    try {
        const guard = await requireSeller(req);
        if (!guard.ok) return guard.response;
        
        try {
            await guardFeatureAccess(guard.kitchen.id, 'digital_khata');
        } catch (error) {
            if (error instanceof PlanFeatureError) {
                return NextResponse.json({ error: error.message }, { status: 403 });
            }
            throw error;
        }

        const body = await req.json();
        const parsed = createKhataSchema.safeParse(body);

        if (!parsed.success) {
            return NextResponse.json({ error: "Invalid data", details: parsed.error.flatten() }, { status: 400 });
        }

        const data = parsed.data;

        const [entry] = await db.insert(khataEntries).values({
            kitchenId: guard.kitchen.id,
            cookId: guard.user.id,
            entryType: data.entryType as any,
            category: data.category,
            description: data.description,
            amountRs: data.amountRs.toString(),
            isCredit: data.isCredit,
            entryDate: data.entryDate,
            isAutoGenerated: false,
        }).returning();

        return NextResponse.json({ success: true, entry });
    } catch (error) {
        logger.error("Failed to create khata entry", { error });
        return NextResponse.json({ error: "Internal Server Error" }, { status: 500 });
    }
}
