import { db } from "@/lib/db";
import { commissionLedger, khataEntries } from "@/lib/db/schema";
import { getKitchenPlanAccess } from "@/lib/plans/plan-access";
import { incrementOrderCount } from "@/services/plan-usage.service";
import { logger } from "@/lib/utils/logger";

/**
 * Records commission for a completed order.
 * Called when order status changes to COMPLETED.
 * Also increments the monthly order counter and auto-creates khata entries for Elite.
 */
export async function recordCommission(
    orderId: string,
    kitchenId: string,
    cookId: string,
    orderAmountRs: number
): Promise<void> {
    try {
        const access = await getKitchenPlanAccess(kitchenId);
        const rate = access.getCommissionRate();
        const commissionAmount = Math.round(orderAmountRs * rate * 100) / 100;
        const netAmount = orderAmountRs - commissionAmount;

        // 1. Insert commission ledger entry (append-only)
        await db.insert(commissionLedger).values({
            orderId,
            kitchenId,
            cookId,
            planId: access.planId ?? 'starter',
            orderAmountRs: orderAmountRs.toString(),
            commissionRate: rate.toString(),
            commissionAmountRs: commissionAmount.toString(),
            netAmountRs: netAmount.toString(),
            status: 'RECORDED',
        });

        // 2. Increment monthly order counter
        if (access.subscription) {
            await incrementOrderCount(access.subscription.id);
        }

        // 3. Auto-generate Khata entries for plans with digital_khata
        if (access.hasFeature('digital_khata')) {
            await autoKhataEntry(kitchenId, cookId, orderId, orderAmountRs, commissionAmount);
        }

        logger.info("Commission recorded", {
            orderId, kitchenId, rate,
            commission: commissionAmount,
            net: netAmount,
        });
    } catch (error) {
        logger.error("Failed to record commission", { orderId, kitchenId, error });
        throw error;
    }
}

async function autoKhataEntry(
    kitchenId: string,
    cookId: string,
    orderId: string,
    orderAmountRs: number,
    commissionAmountRs: number
) {
    const now = new Date();
    const entryDate = now.toISOString().split('T')[0];

    // 1. Record Income
    await db.insert(khataEntries).values({
        kitchenId,
        cookId,
        entryType: 'INCOME',
        category: 'Order Income',
        description: `Revenue from Order ${orderId.slice(-6)}`,
        amountRs: orderAmountRs.toString(),
        isCredit: true,
        referenceId: orderId,
        referenceType: 'ORDER',
        entryDate: entryDate as any,
        isAutoGenerated: true,
    });

    // 2. Record Commission Expense if applicable
    if (commissionAmountRs > 0) {
        await db.insert(khataEntries).values({
            kitchenId,
            cookId,
            entryType: 'COMMISSION',
            category: 'Platform Fee',
            description: `Smart Tiffin Fee for Order ${orderId.slice(-6)}`,
            amountRs: commissionAmountRs.toString(),
            isCredit: false,
            referenceId: orderId,
            referenceType: 'ORDER',
            entryDate: entryDate as any,
            isAutoGenerated: true,
        });
    }
}
