import { db } from "@/lib/db";
import { commissionLedger, subscriptions, khataEntries } from "@/lib/db/schema";
import { getKitchenPlanAccess } from "@/lib/plans/plan-access";
import { eq, sql } from "drizzle-orm";
import { logger } from "@/lib/utils/logger";

export async function recordCommission(
    orderId: string,
    kitchenId: string,
    cookId: string,
    orderAmountRs: number
): Promise<void> {
    try {
        const access = await getKitchenPlanAccess(kitchenId);
        const rate = access.getCommissionRate();
        const commissionAmount = Math.round(orderAmountRs * rate * 100) / 100;
        const netAmount = orderAmountRs - commissionAmount;

        // Insert commission record
        await db.insert(commissionLedger).values({
            orderId,
            kitchenId,
            cookId,
            planId: access.planId,
            orderAmountRs: orderAmountRs.toString(),
            commissionRate: rate.toString(),
            commissionAmountRs: commissionAmount.toString(),
            netAmountRs: netAmount.toString(),
            status: 'PENDING',
        });

        // Increment monthly order counter if subscription exists
        if (access.subscription) {
            await db.update(subscriptions)
                .set({
                    ordersUsedThisMonth: sql`${subscriptions.ordersUsedThisMonth} + 1`,
                    updatedAt: new Date(),
                })
                .where(eq(subscriptions.id, access.subscription.id));
        }

        // Auto-generate Khata entry if Elite plan
        if (access.hasFeature('digital_khata')) {
            await autoKhataEntry(kitchenId, cookId, orderId, orderAmountRs, commissionAmount);
        }
        
    } catch (error) {
        logger.error("Failed to record commission", { orderId, kitchenId, error });
        throw error;
    }
}

async function autoKhataEntry(
    kitchenId: string,
    cookId: string,
    orderId: string,
    orderAmountRs: number,
    commissionAmountRs: number
) {
    const now = new Date();
    
    // 1. Record Income
    await db.insert(khataEntries).values({
        kitchenId,
        cookId,
        entryType: 'INCOME',
        category: 'Order Income',
        description: `Revenue from Order ${orderId.slice(-6)}`,
        amountRs: orderAmountRs.toString(),
        isCredit: true,
        referenceId: orderId,
        referenceType: 'ORDER',
        entryDate: now.toISOString().split('T')[0] as any, // "YYYY-MM-DD" mapping
        isAutoGenerated: true,
    });

    // 2. Record Commission Expense if applicable
    if (commissionAmountRs > 0) {
        await db.insert(khataEntries).values({
            kitchenId,
            cookId,
            entryType: 'COMMISSION',
            category: 'Platform Fee',
            description: `Smart Tiffin Fee for Order ${orderId.slice(-6)}`,
            amountRs: commissionAmountRs.toString(),
            isCredit: false,
            referenceId: orderId,
            referenceType: 'ORDER',
            entryDate: now.toISOString().split('T')[0] as any,
            isAutoGenerated: true,
        });
    }
}
